# Generated by Django 4.2 on 2023-04-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='linenos',
            field=models.BooleanField(default=False),
        ),
    ]
